# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e064aa0dc7ad2a4c1415981a0b8534bdae068bc261ce771a7a01e5f9e0800660506473dfdf0b70aa9a7ec00b7ab3e2a6b4afbd3f1353086a93bac4632a980d60

test:
  secret_key_base: 0c91960808a5592fc78cf9181624822c187838de0b0b0bf8a3fa56fc53ebce050cd3a7762a227de6e5d1f8eace3af2c0bd167c2a211f18cdbed9ba9f4c8638cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
